"""Add is_read column to Email model

Revision ID: eede45260f09
Revises: c133b6dd4afb
Create Date: 2025-08-18 11:58:12.345678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eede45260f09'
down_revision = 'c133b6dd4afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        # --- THIS IS THE FIX ---
        # We add server_default='0' to tell the database to set all
        # existing rows to False (0 for a boolean in SQLite).
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###